FROM nvidia/cuda:12.0.1-devel-ubuntu22.04

RUN apt-get update -y
RUN apt-get install -y vim
RUN apt-get install -y wget
RUN apt-get install -y curl
RUN apt-get install -y build-essential
RUN apt-get install -y procps
RUN apt-get install -y openssh-server
RUN apt-get install -y sshfs

RUN wget \
    https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh \
    && mkdir /root/.conda \
    && bash Miniconda3-latest-Linux-x86_64.sh -b  -p /opt/conda  \
    && rm -f Miniconda3-latest-Linux-x86_64.sh \
    # && /opt/conda/bin/conda clean -tipsy  \
    && ln -s /opt/conda/etc/profile.d/conda.sh /etc/profile.d/conda.sh \
    && echo ". /opt/conda/etc/profile.d/conda.sh" >> ~/.bashrc  \
    && echo "conda activate base" >> ~/.bashrc

ENV PATH="/opt/conda/condabin:${PATH}"
SHELL ["/bin/bash", "--login", "-c"]
RUN conda init bash
RUN conda create --name py39 python=3.9.5
COPY ./scripts/py39_pkgs.sh /root/install_pkg.sh
RUN conda activate py39 \
    && sh /root/install_pkg.sh 
RUN conda activate py39 \
    # && conda install pytorch torchvision torchaudio cudatoolkit=11.3 -c pytorch \
    && pip install torch torchvision torchaudio \
    && pip install hyperopt

# ====================================== start adding you conda environment  ======================================
RUN conda create --name qinjie python=3.9.5
COPY ./my_scripts/install_env.sh /root/install_env.sh 
RUN conda activate qinjie \
    && sh /root/install_env.sh 
# ======================================**************** end ****************====================================== 

ENV DIRPATH /home/ubuntu
WORKDIR $DIRPATH
# ENTRYPOINT ["/bin/bash", "-c", "source /opt/conda/etc/profile.d/conda.sh && conda activate py39 && python "]